package edu.bu.cs611.portfoliostocksystem.view;

import java.beans.PropertyChangeEvent;

import edu.bu.cs611.portfoliostocksystem.controller.ExampleController;
import javax.swing.JOptionPane;

/**
 *
 * @author Sophie jwz16@bu.edu
 */
public class ExampleView extends javax.swing.JFrame implements AbstractView {

  private final ExampleController controller;

  /**
   * Creates new form ExampleView
   */
  public ExampleView(ExampleController controller) {
    initComponents();

    this.controller = controller;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnExample = new javax.swing.JButton();
    labelExample = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));

    btnExample.setText("Click Me");
    btnExample.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnExampleMouseClicked(evt);
      }
    });

    labelExample.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    labelExample.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    labelExample.setText("Example Text");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(129, Short.MAX_VALUE)
        .addComponent(labelExample, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        .addContainerGap(129, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnExample, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(75, 75, 75)
        .addComponent(labelExample, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(39, 39, 39)
        .addComponent(btnExample, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(125, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnExampleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExampleMouseClicked
    var resp = controller.exampleAction("a", "a");
    
    if (resp.success) {
      // DO SOMETHING
      JOptionPane.showMessageDialog(this, "Action success, data from action response: " + resp.data);
    } else {
      // DO SOMETHING ELSE
      JOptionPane.showMessageDialog(this, "Action failed, data from action response: " + resp.data);
    }
  }//GEN-LAST:event_btnExampleMouseClicked

  @Override
  public void modelPropertyChange(PropertyChangeEvent evt) {
    // DO SOMETHING to check which property has been changed in evt.
    
    if (evt.getPropertyName().equals("text")) {
      labelExample.setText((String) evt.getNewValue());
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnExample;
  private javax.swing.JLabel labelExample;
  // End of variables declaration//GEN-END:variables
}
